<a href="https://colab.research.google.com/github/GabsCavalcant/Aplicacao-Utilizando-llm-Rn-etc/blob/main/FiltrandoDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np

from pandas import DataFrame, Series

In [26]:
np.random.seed(25)

indice = ['l2','l3','l4','l5','l6']
coluna = ['c2','c3','c4','c5','c6']

df = DataFrame(np.random.rand(25).reshape((5,5)),
               index = indice,
               columns = coluna)

In [27]:
df

          c2        c3        c4        c5        c6
l2  0.870124  0.582277  0.278839  0.185911  0.411100
l3  0.117376  0.684969  0.437611  0.556229  0.367080
l4  0.402366  0.113041  0.447031  0.585445  0.161985
l5  0.520719  0.326051  0.699186  0.366395  0.836375
l6  0.481343  0.516502  0.383048  0.997541  0.514244

In [28]:
df < .2

       c2     c3     c4     c5     c6
l2  False  False  False   True  False
l3   True  False  False  False  False
l4  False   True  False  False   True
l5  False  False  False  False  False
l6  False  False  False  False  False

In [29]:
indice = ['l2','l3','l4','l5','l6']
series_obj = Series(np.arange(5), index=indice)

filtro = series_obj > 1

series_obj[filtro]

l4    2
l5    3
l6    4
dtype: int64

In [32]:
series_obj[['l2', 'l4','l5']] = 8

series_obj

l2    8
l3    1
l4    8
l5    8
l6    4
dtype: int64