<a href="https://colab.research.google.com/github/GabsCavalcant/Aplicacao-Utilizando-llm-Rn-etc/blob/main/Regress%C3%A3o_Classifica%C3%A7%C3%A3o_Binaria_Modelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Leitura do csv
import pandas as pd

data = pd.read_csv("churnData.csv")

In [ ]:
#drop Colum table
data = data.drop(columns= ['CustomerID'])

In [ ]:
#Visualização Basica dos dados
data

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
440828,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

In [ ]:
#transformando a tabela Gender em binario.
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])



data = pd.get_dummies(data, ['Subscription Type','Contract Length'])

In [ ]:
data = data.dropna()

In [ ]:
x = data.drop('Churn', axis=1) #FEATURE
y = data[('Churn')] #TARGET

In [ ]:
y

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ...
440828    0.0
440829    0.0
440830    0.0
440831    0.0
440832    0.0
Name: Churn, Length: 440832, dtype: float64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#treinamento do modelo
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size= 0.2, random_state=42)

In [ ]:
data.corr()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Annual,Contract Length_Monthly,Contract Length_Quarterly
Age,1.000000,-0.031419,-0.011630,-0.007190,0.158451,0.061738,-0.084684,0.028980,0.218394,0.004768,-0.002873,-0.001847,-0.034986,0.086909,-0.035617
Gender,-0.031419,1.000000,0.007978,0.007978,-0.091212,-0.048449,0.066138,0.134786,-0.175395,-0.000725,0.003189,-0.002469,0.029391,-0.067611,0.025533
Tenure,-0.011630,0.007978,1.000000,-0.026800,-0.027640,-0.016588,0.019006,-0.006903,-0.051919,0.027270,-0.015415,-0.011580,0.009021,-0.020637,0.007744
Usage Frequency,-0.007190,0.007978,-0.026800,1.000000,-0.022013,-0.014470,0.018631,-0.004662,-0.046101,0.000096,0.000149,-0.000244,0.006943,-0.017820,0.007534
Support Calls,0.158451,-0.091212,-0.027640,-0.022013,1.000000,0.162889,-0.221594,0.077684,0.574267,0.010780,-0.006219,-0.004453,-0.091068,0.223242,-0.090289
Payment Delay,0.061738,-0.048449,-0.016588,-0.014470,0.162889,1.000000,-0.121044,0.042708,0.312129,0.005085,-0.004229,-0.000805,-0.049697,0.122674,-0.049961
Total Spend,-0.084684,0.066138,0.019006,0.018631,-0.221594,-0.121044,1.000000,-0.056890,-0.429355,-0.008469,0.003882,0.004501,0.068365,-0.166916,0.067234
Last Interaction,0.028980,0.134786,-0.006903,-0.004662,0.077684,0.042708,-0.056890,1.000000,0.149616,0.000615,-0.000438,-0.000171,-0.023342,0.057563,-0.023421
Churn,0.218394,-0.175395,-0.051919,-0.046101,0.574267,0.312129,-0.429355,0.149616,1.000000,0.020526,-0.011072,-0.009247,-0.175965,0.433553,-0.176244
Subscription Type_Basic,0.004768,-0.000725,0.027270,0.000096,0.010780,0.005085,-0.008469,0.000615,0.020526,1.000000,-0.494377,-0.495506,-0.001345,0.009607,-0.006461
Subscription Type_Premium,-0.002873,0.003189,-0.015415,0.000149,-0.006219,-0.004229,0.003882,-0.000438,-0.011072,-0.494377,1.000000,-0.510065,0.000636,-0.003715,0.002382
Subscription Type_Standard,-0.001847,-0.002469,-0.011580,-0.000244,-0.004453,-0.000805,0.004501,-0.000171,-0.009247,-0.495506,-0.510065,1.000000,0.000695,-0.005794,0.004013
Contract Length_Annual,-0.034986,0.029391,0.009021,0.006943,-0.091068,-0.049697,0.068365,-0.023342,-0.175965,-0.001345,0.000636,0.000695,1.000000,-0.406830,-0.670020
Contract Length_Monthly,0.086909,-0.067611,-0.020637,-0.017820,0.223242,0.122674,-0.166916,0.057563,0.433553,0.009607,-0.003715,-0.005794,-0.406830,1.000000,-0.405549
Contract Length_Quarterly,-0.035617,0.025533,0.007744,0.007534,-0.090289,-0.049961,0.067234,-0.023421,-0.176244,-0.006461,0.002382,0.004013,-0.670020,-0.405549,1.000000

In [ ]:
#treinando testando a acuracia do modelo
modelo = LogisticRegression(max_iter=1000)
modelo.fit(x_train,y_train)

previsao = modelo.predict(x_test)

print(f"Acuracia : {accuracy_score(y_test, previsao)}")

Acuracia : 0.8964351741581317

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
data

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Annual,Contract Length_Monthly,Contract Length_Quarterly
0,30.0,0,39.0,14.0,5.0,18.0,932.00,17.0,1.0,False,False,True,True,False,False
1,65.0,0,49.0,1.0,10.0,8.0,557.00,6.0,1.0,True,False,False,False,True,False
2,55.0,0,14.0,4.0,6.0,18.0,185.00,3.0,1.0,True,False,False,False,False,True
3,58.0,1,38.0,21.0,7.0,7.0,396.00,29.0,1.0,False,False,True,False,True,False
4,23.0,1,32.0,20.0,5.0,8.0,617.00,20.0,1.0,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,42.0,1,54.0,15.0,1.0,3.0,716.38,8.0,0.0,False,True,False,True,False,False
440829,25.0,0,8.0,13.0,1.0,20.0,745.38,2.0,0.0,False,True,False,True,False,False
440830,26.0,1,35.0,27.0,1.0,5.0,977.31,9.0,0.0,False,False,True,False,False,True
440831,28.0,1,55.0,14.0,2.0,0.0,602.55,2.0,0.0,False,False,True,False,False,True
440832,31.0,1,48.0,20.0,1.0,14.0,567.77,21.0,0.0,False,True,False,False,False,True

In [ ]:
#texte de um dado epecifico

dados_teste = {
    'Age': [40],
    'Gender': [1],
    'Tenure': [5],
    'Usage Frequency': [5],
    'Support Calls': [1],
    'Payment Delay': [15],
    'Total Spend': [100],
    'Last Interaction': [10],
    'Subscription Type_Basic': [0],
    'Subscription Type_Premium': [1],
    'Subscription Type_Standard': [0],
    'Contract Length_Annual': [1],
    'Contract Length_Monthly': [0],
    'Contract Length_Quarterly': [0]
}

perfil_teste = pd.DataFrame(dados_teste)

In [ ]:
previsao = modelo.predict(perfil_teste)
prob = modelo.predict_proba(perfil_teste)

print(f"Resultado: {'Churn' if previsao[0] == 1 else 'Fica'}")
print(f"Probabilidade de sair: {prob[0][1]:.2%}")

Resultado: Churn
Probabilidade de sair: 84.40%