<a href="https://colab.research.google.com/github/GabsCavalcant/Aplicacao-Utilizando-llm-Rn-etc/blob/main/RemocaoDadosDuplicaos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

from pandas import DataFrame,Series

In [12]:
dados = {

    'coluna 1' : [1,1,2,2,3,3],
    'coluna 2' : ['a','a','b','b','c','c'],
    'coluna 3' : ['A','A','B',"B",'C','B']
}


df = DataFrame(dados)
df

   coluna 1 coluna 2 coluna 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        B

In [13]:
df.duplicated()

0    False
1     True
2    False
3     True
4    False
5    False
dtype: bool

In [14]:
df.drop_duplicates()

   coluna 1 coluna 2 coluna 3
0         1        a        A
2         2        b        B
4         3        c        C
5         3        c        B

In [16]:
df.drop_duplicates(inplace= True)

In [19]:
df

   coluna 1 coluna 2 coluna 3
0         1        a        A
2         2        b        B
4         3        c        C
5         3        c        B

In [ ]:
dados = {

    'coluna 1' : [1,1,2,2,3,3],
    'coluna 2' : ['a','a','b','b','c','c'],
    'coluna 3' : ['A','A','B',"B",'C','B']
}


df = DataFrame(dados)
df